export const EDIT_CIRCLE = 'EDIT_CIRCLE';
export const CLAIM_PAYOUT_SPOT_ON_CIRCLE = 'CLAIM_PAYOUT_SPOT_ON_CIRCLE';
export const ADD_CIRCLE = 'ADD_CIRCLE';
export const ADD_CIRCLES = 'ADD_CIRCLES';
export const HANDLE_FIND_CIRCLES_SUCCESS = 'HANDLE_FIND_CIRCLES_SUCCESS';
export const BEGIN_EDITING_CIRCLE_SAVINGS_GOAL_FOR_USER = 'BEGIN_EDITING_CIRCLE_SAVINGS_GOAL_FOR_USER';
export const STOP_EDITING_CIRCLE_SAVINGS_GOAL_FOR_USER = 'STOP_EDITING_CIRCLE_SAVINGS_GOAL_FOR_USER';
export const EDIT_CIRCLE_SAVINGS_GOAL_FOR_USER = 'EDIT_CIRCLE_SAVINGS_GOAL_FOR_USER';
