export const SHOW_ADD_USER_MODAL = 'SHOW_ADD_USER_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const UPDATE_ADD_USER_EMAIL = 'UPDATE_ADD_USER_EMAIL';
export const SUBMIT_ADD_USER = 'SUBMIT_ADD_USER';
