export const EDIT_TODO_TEXT = 'EDIT_TODO_TEXT';
export const CREATE_TODO = 'CREATE_TODO';
export const TOGGLE_TODO_COMPLETED_STATE = 'TOGGLE_TODO_COMPLETED_STATE';
export const DELETE_TODO = 'DELETE_TODO';
export const START_EDITING_TODO = 'START_EDITING_TODO';
export const STOP_EDITING_TODO = 'STOP_EDITING_TODO';
