export const SHOW_TOOLTIP_AT_ELEMENT = 'SHOW_TOOLTIP_AT_ELEMENT';
export const DESTROY_TOOLTIP = 'DESTROY_TOOLTIP';
export const DESTROY_ALL_TOOLTIPS = 'DESTROY_ALL_TOOLTIPS';
export const OPEN_HEADER_DROPDOWN = 'OPEN_HEADER_DROPDOWN';
export const CLOSE_HEADER_DROPDOWN = 'CLOSE_HEADER_DROPDOWN';
export const OPEN_NOTIFICATION_DROPDOWN = 'OPEN_NOTIFICATION_DROPDOWN';
export const CLOSE_NOTIFICATION_DROPDOWN = 'CLOSE_NOTIFICATION_DROPDOWN';
export const CLOSE_ALL_NAV_DROPDOWNS = 'COSE_ALL_NAV_DROPDOWNS';
