export const OPEN_EDIT_USER_PANEL = 'OPEN_EDIT_USER_PANEL';
export const CLOSE_EDIT_USER_PANEL = 'CLOsE_EDIT_USER_PANEL';
export const START_EDITING_ATTR_FOR_USER = 'START_EDITING_ATTR_FOR_USER';
export const EDIT_USER = 'EDIT_USER';
